// PLACEHOLDER — generated by `flutterfire configure`, which will overwrite
// this file with the real project credentials once P3-M4's Firebase project
// is set up. Until that happens every value below stays 'PLACEHOLDER', so
// `main.dart` detects it (see `isPlaceholderFirebaseOptions`) and skips
// `Firebase.initializeApp`, keeping the app fully usable without push.
//
// To turn push on: run `flutterfire configure` from the repo root, let it
// overwrite this file, then rebuild the app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform — '
          'run flutterfire configure.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
  );

  static const ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
    iosBundleId: 'PLACEHOLDER',
  );
}
